addSbtPlugin("com.eed3si9n"     % "sbt-assembly"         % "0.14.10")
addSbtPlugin("io.get-coursier"  % "sbt-coursier"         % "1.1.0-M13")
addSbtPlugin("au.com.onegeek"   %% "sbt-dotenv"          % "2.0.117")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"         % "2.2.1")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.9.11")
